# Generated by Django 4.2.5 on 2024-06-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_faculty_name_customuser_is_lecturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='course',
            field=models.CharField(choices=[('BIST', 'Bachelor of Information System and Technology'), ('BCS', 'Bachelor of Computer Science'), ('BSE', 'Bachelor of Software Engineering'), ('BLIS', 'Bachelor of Library and Information Systems')], default='BIST', max_length=100),
        ),
    ]
