# Generated by Django 5.0.4 on 2024-06-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sFirstName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sLastName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sMiddleName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
