# Generated by Django 5.0.4 on 2024-06-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_sfirstname_customuser_slastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
