# Generated by Django 5.0.4 on 2024-07-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_sno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='sMiddleName',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Staff_ID',
            field=models.CharField(max_length=15),
        ),
    ]
