# Generated by Django 5.0.6 on 2024-09-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_sharedreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='course',
            field=models.CharField(choices=[('BIS', 'Bachelor of Information Systems'), ('BITC', 'Bachelor of Information Techonology'), ('DCS', 'Diploma in Computer Science')], default='BIST', max_length=100),
        ),
    ]
