# Generated by Django 4.2.5 on 2024-05-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='latitude',
            field=models.FloatField(default=0.3324),
        ),
        migrations.AddField(
            model_name='lecture',
            name='longitude',
            field=models.FloatField(default=32.5705),
        ),
    ]
