# Generated by Django 4.2.5 on 2024-06-03 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0003_alter_lecture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=7200)),
        ),
        migrations.AddField(
            model_name='lecture',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
