# Generated by Django 4.2.5 on 2024-06-30 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0005_lecture_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='status',
        ),
    ]
