# Generated by Django 4.2.5 on 2024-06-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_courseunit_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseunit',
            name='name',
        ),
        migrations.AlterField(
            model_name='courseunit',
            name='code',
            field=models.CharField(choices=[('CS101', 'Introduction to IST'), ('CS102', 'Data Structures'), ('CS103', 'Algorithms'), ('CS104', 'Operating Systems'), ('CS105', 'Database Systems'), ('CS106', 'Software Engineering'), ('CS107', 'Artificial Intelligence'), ('CS108', 'Machine Learning')], max_length=10),
        ),
        migrations.AlterField(
            model_name='courseunit',
            name='course',
            field=models.CharField(choices=[('BIST', 'Bachelor of Information System and Technology'), ('BCS', 'Bachelor of Computer Science'), ('BSE', 'Bachelor of Software Engineering'), ('BLIS', 'Bachelor of Library and Information Systems')], max_length=50),
        ),
    ]
