# Generated by Django 4.2.5 on 2024-06-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_courseunit_name_alter_courseunit_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseunit',
            name='code',
            field=models.CharField(choices=[('CS101', 'Introduction to IST'), ('CS102', 'Data Structures'), ('CS103', 'Algorithms'), ('CS104', 'Operating Systems'), ('CS105', 'Database Systems'), ('CS106', 'Software Engineering'), ('CS107', 'Artificial Intelligence'), ('CS108', 'Machine Learning')], max_length=50),
        ),
    ]
